### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by kosssi** [whisller/IrcBotBundle#9]
Hello

I'm testing with de README demo but a ErrorException when i lauch '!bot hello kosssi'

[ErrorException]  
  Catchable Fatal Error: Argument 1 passed to Whisnet\IrcBotBundle\EventListener\Plugins\Commands\CommandListener::__construct() must implement interface Whisnet\Irc  
  BotBundle\Connection\ConnectionInterface, none given, called in */IrcBot/app/cache/dev/appDevDebugProjectContainer.php on line 2612 and defined in */IrcBot/vendor/whisller/irc-bot-bundle/Whisnet/IrcBotBundle/EventListener/Plugins/Commands/CommandListener.php line 23

**Comment by phillpafford** [comment]
There is an error in the readme Hello example:

current:

$this->sendMessage($event, array($event->getChannel()), $msg);

fix ( remove the event paramater ):

$this->sendMessage(array($event->getChannel()), $msg);

**Comment by kosssi** [comment]
I know that but it's before.

I write a TestIrcBot if you can see where is my mistake...

**Comment by phillpafford** [comment]
I don't see the https://github.com/whisller/IrcBotBundle configured in your symfony build, am I missing something? The example wont work unless you include the bundle

**Comment by kosssi** [comment]
TestIrcBot / composer.json : 
    "whisller/irc-bot-bundle": "*"

TestIrcBot / app / AppKernel.php : 
    new Whisnet\IrcBotBundle\WhisnetIrcBotBundle(),
    new kosssi\PreBundle\PreBundle(),

TestIrcBot / app / config / config.yml : 
    whisnet_irc_bot:
        connection_class: Whisnet\IrcBotBundle\Connection\Socket
        host: irc.freenode.net
        port: 6667
        command_prefix: !bot
        user:
            username: IrcBotBunle
            mode: 8
        channels: ["#test-irc", "#test-other-irc"]

and 2 files : 
TestIrcBot / src / kosssi / PreBundle / EventListener / HelloListener.php
TestIrcBot / src / kosssi / PreBundle / Resources / config / services.xml

I think it's good !!! No ?

**Comment by kosssi** [comment]
ok, the probleme is simple ...

i add this in service.xml :
< argument type="service" id="whisnet_irc_bot.connection" / >
